name: VyOS v1.4 Rolling Release

on: workflow_dispatch
 
env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: sagitta
  ARCHITECTURE: amd64
  BUILD_BY: thomas@flomesh.cn
  BUILD_TYPE: release
  VERSION: 1.4
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:sagitta
      options: --workdir /vyos --privileged

    steps:
      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $GIT_CLONE_URL

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version $VERSION-$(date +%Y%m%d%H%M)

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso
          path: vyos-build/build/vyos-${{ env.VERSION }}-*.iso
